(self.__BUILD_MANIFEST = (function (
  a,
  s,
  e,
  c,
  t,
  n,
  o,
  i,
  d,
  r,
  u,
  p,
  f,
  h,
  b,
  g,
  m,
  k,
  q,
  j,
  l,
  z,
  x,
  v,
  _,
  y,
  I,
  B
) {
  return {
    __rewrites: { beforeFiles: [], afterFiles: [], fallback: [] },
    "/50vezeseducacaofinanceira": [
      "static/chunks/3661-869c9951347c5bc3.js",
      "static/css/a447fdccfd7331cf.css",
      "static/chunks/pages/50vezeseducacaofinanceira-60fb286288b126e0.js",
    ],
    "/_error": ["static/chunks/pages/_error-c2edf0923b135656.js"],
    "/antecipacao-saque-fgts": [
      h,
      "static/css/d3ff35e6c8a97ec6.css",
      "static/chunks/pages/antecipacao-saque-fgts-018602cfb4a307db.js",
    ],
    "/autonomos": [
      s,
      e,
      c,
      t,
      g,
      m,
      k,
      "static/css/228dc2daa297c128.css",
      "static/chunks/pages/autonomos-32d6afed95d43a7d.js",
    ],
    "/baixe-pagbank-fgts": [
      s,
      e,
      q,
      "static/css/998cd8ac1fc08b37.css",
      "static/chunks/pages/baixe-pagbank-fgts-157b12c3e38b7f26.js",
    ],
    "/beleza-e-estetica": [
      "static/chunks/pages/beleza-e-estetica-3928787f155429a6.js",
    ],
    "/calculadora-de-desconto": [
      s,
      e,
      u,
      j,
      "static/css/4739ba7f70a9b173.css",
      "static/chunks/pages/calculadora-de-desconto-882071b55e7e5fac.js",
    ],
    "/campanha-pix-vtex": [
      u,
      p,
      "static/css/4d9ce7677560a491.css",
      "static/chunks/pages/campanha-pix-vtex-2bfdcba9d86c6133.js",
    ],
    "/cashback-pagbank-na-maquina": [
      "static/css/9631be5b01694f5d.css",
      "static/chunks/pages/cashback-pagbank-na-maquina-ca959b0090e6f058.js",
    ],
    "/cashback-turbinado": [
      "static/chunks/pages/cashback-turbinado-9e2e21427bd300ab.js",
    ],
    "/clientes-reais": [
      h,
      "static/css/13b8231f62886434.css",
      "static/chunks/pages/clientes-reais-246be687a04ae5a2.js",
    ],
    "/combo-maquininhas-e-cartao": [
      s,
      e,
      c,
      t,
      r,
      a,
      i,
      d,
      b,
      "static/chunks/pages/combo-maquininhas-e-cartao-d3f7b42b72203339.js",
    ],
    "/consignado-inss": [
      "static/chunks/pages/consignado-inss-23552887e95968c4.js",
    ],
    "/contato": [
      u,
      p,
      "static/css/c28cbcd805ee49eb.css",
      "static/chunks/pages/contato-1311e5e5bf4d5217.js",
    ],
    "/diversificacao-com-fundos": [
      u,
      p,
      "static/css/2a18dd2c41d4c3bf.css",
      "static/chunks/pages/diversificacao-com-fundos-a9587640d300be45.js",
    ],
    "/emprestimo-consignado-siape": [
      "static/css/08282ca75767f0b4.css",
      "static/chunks/pages/emprestimo-consignado-siape-3fc3a15c8d19251c.js",
    ],
    "/evento": [
      u,
      p,
      "static/css/b78e66e2b681f0bd.css",
      "static/chunks/pages/evento-243aad32d443ac37.js",
    ],
    "/folha-de-pagamento": [
      u,
      p,
      "static/css/77fc1003bf3ec8c2.css",
      "static/chunks/pages/folha-de-pagamento-57443b9b914a7a35.js",
    ],
    "/gerador-url-eventos": [
      u,
      "static/css/2810f8d1f1ea2c36.css",
      "static/chunks/pages/gerador-url-eventos-d881e9dde282d2e0.js",
    ],
    "/maquinas-cartao-taxas-faturamento": [
      s,
      e,
      c,
      t,
      q,
      l,
      i,
      d,
      "static/css/613f4cccd92046b1.css",
      "static/chunks/pages/maquinas-cartao-taxas-faturamento-abffdf072cf9d537.js",
    ],
    "/maquinas-de-cartao": [
      s,
      e,
      c,
      t,
      r,
      a,
      i,
      d,
      b,
      "static/chunks/pages/maquinas-de-cartao-1d1d55e5f758eced.js",
    ],
    "/maquinas-de-cartao/condicoes-especiais": [
      s,
      e,
      c,
      t,
      r,
      a,
      i,
      d,
      "static/css/d85dbd4cbca42412.css",
      "static/chunks/pages/maquinas-de-cartao/condicoes-especiais-6159533a7bcfd9d0.js",
    ],
    "/maquinas-de-cartao/moderninhas": [
      s,
      e,
      c,
      t,
      r,
      a,
      i,
      d,
      b,
      "static/chunks/pages/maquinas-de-cartao/moderninhas-e593a0f77841229e.js",
    ],
    "/maquinas-de-cartao/promo-especial": [
      "static/chunks/pages/maquinas-de-cartao/promo-especial-f1234f0fd972147f.js",
    ],
    "/maquinas-de-cartao/sazonal": [
      s,
      e,
      c,
      t,
      r,
      a,
      i,
      d,
      b,
      "static/chunks/pages/maquinas-de-cartao/sazonal-08b0bc4644dd49b1.js",
    ],
    "/maquinas-de-cartao/tap-on": [
      s,
      e,
      c,
      t,
      r,
      a,
      i,
      d,
      "static/css/feabd6c3a8cdcd31.css",
      "static/chunks/pages/maquinas-de-cartao/tap-on-6b3c82f1ccc2b0a6.js",
    ],
    "/maquinas-de-cartao/v2": [
      "static/chunks/pages/maquinas-de-cartao/v2-e28207b7a3cfb7d7.js",
    ],
    "/maquinas-de-cartao-promo-elo": [
      "static/chunks/pages/maquinas-de-cartao-promo-elo-f0d0b53f401a093f.js",
    ],
    "/maquininha-de-cartao-menores-taxas": [
      "static/chunks/6256-4ea5fe83cff22357.js",
      g,
      "static/css/7f86d1ce42bbb672.css",
      "static/chunks/pages/maquininha-de-cartao-menores-taxas-cf11636569efa8d8.js",
    ],
    "/maquininha-pagbank-oferta-exclusiva": [
      "static/chunks/29107295-46d7d1929d94c0a9.js",
      s,
      e,
      c,
      t,
      r,
      l,
      "static/chunks/6321-09f5562296bb931a.js",
      i,
      d,
      g,
      m,
      k,
      "static/css/c3a7227decc6b4ac.css",
      "static/chunks/pages/maquininha-pagbank-oferta-exclusiva-ba02080addfb822a.js",
    ],
    "/maquininhas-de-cartao-melhores-taxas": [
      s,
      e,
      c,
      t,
      r,
      a,
      i,
      d,
      "static/css/1c4473b45fd0cdf2.css",
      "static/chunks/pages/maquininhas-de-cartao-melhores-taxas-b0899a440fbaab82.js",
    ],
    "/maquininhas-taxas-planos": [
      "static/chunks/pages/maquininhas-taxas-planos-32c8f7baf75dd7fc.js",
    ],
    "/motoristas-e-taxistas": [
      "static/chunks/pages/motoristas-e-taxistas-5bbeddb8848ac149.js",
    ],
    "/oferta-minizinha-chip3-do-pagbank-melhores-taxas-squeeze": [
      a,
      n,
      o,
      f,
      "static/css/246f7299ead84575.css",
      "static/chunks/pages/oferta-minizinha-chip3-do-pagbank-melhores-taxas-squeeze-2d221c4f84e0473f.js",
    ],
    "/oferta-minizinha-chip3-do-pagbank-squeeze": [
      a,
      n,
      o,
      "static/css/9e6f905610a2890d.css",
      "static/chunks/pages/oferta-minizinha-chip3-do-pagbank-squeeze-0e4b89da0790e2b1.js",
    ],
    "/oferta-minizinha-chip3-do-pagseguro-squeeze": [
      "static/chunks/pages/oferta-minizinha-chip3-do-pagseguro-squeeze-efe476a344cccbe4.js",
    ],
    "/oferta-minizinha-nfc2-do-pagbank": [
      "static/chunks/pages/oferta-minizinha-nfc2-do-pagbank-a78850320325b96b.js",
    ],
    "/oferta-minizinha-nfc2-do-pagbank-melhores-taxas-squeeze": [
      z,
      a,
      n,
      o,
      "static/css/9651bd7fd341a370.css",
      "static/chunks/pages/oferta-minizinha-nfc2-do-pagbank-melhores-taxas-squeeze-d7e2baa34a1cb6f2.js",
    ],
    "/oferta-minizinha-nfc2-do-pagbank-squeeze": [
      z,
      a,
      n,
      o,
      "static/css/fb38da1a6853eca9.css",
      "static/chunks/pages/oferta-minizinha-nfc2-do-pagbank-squeeze-5644583302236353.js",
    ],
    "/oferta-minizinha-nfc2-do-pagseguro": [
      "static/chunks/pages/oferta-minizinha-nfc2-do-pagseguro-20c1971e4cda4ec3.js",
    ],
    "/oferta-minizinha-nfc2-do-pagseguro-squeeze": [
      "static/chunks/pages/oferta-minizinha-nfc2-do-pagseguro-squeeze-1a4f4c1f1222ee6a.js",
    ],
    "/oferta-moderninha-plus2-do-pagbank-melhores-taxas-squeeze": [
      a,
      n,
      o,
      f,
      "static/css/5c57e16a402262d2.css",
      "static/chunks/pages/oferta-moderninha-plus2-do-pagbank-melhores-taxas-squeeze-641d6fe924fdccc3.js",
    ],
    "/oferta-moderninha-plus2-do-pagbank-squeeze": [
      a,
      n,
      o,
      "static/css/6392dea27ea9639f.css",
      "static/chunks/pages/oferta-moderninha-plus2-do-pagbank-squeeze-b8ac854fe7148cad.js",
    ],
    "/oferta-moderninha-plus2-do-pagseguro-squeeze": [
      "static/chunks/pages/oferta-moderninha-plus2-do-pagseguro-squeeze-8f737c8012d8ee61.js",
    ],
    "/oferta-moderninha-pro-do-pagbank-squeeze": [
      "static/chunks/pages/oferta-moderninha-pro-do-pagbank-squeeze-a3de023b5cb7a3be.js",
    ],
    "/oferta-moderninha-pro-do-pagseguro-squeeze": [
      "static/chunks/pages/oferta-moderninha-pro-do-pagseguro-squeeze-42fb831450aa23a4.js",
    ],
    "/oferta-moderninha-pro2-do-pagbank-melhores-taxas-squeeze": [
      a,
      n,
      o,
      f,
      "static/css/b68729a77fab5715.css",
      "static/chunks/pages/oferta-moderninha-pro2-do-pagbank-melhores-taxas-squeeze-62ce87e67175c54f.js",
    ],
    "/oferta-moderninha-pro2-do-pagbank-squeeze": [
      a,
      n,
      o,
      "static/css/2b49375cee4f96e5.css",
      "static/chunks/pages/oferta-moderninha-pro2-do-pagbank-squeeze-25fa3cd8ff3b931a.js",
    ],
    "/oferta-moderninha-pro2-do-pagseguro-squeeze": [
      "static/chunks/pages/oferta-moderninha-pro2-do-pagseguro-squeeze-cc10adf20b8520f9.js",
    ],
    "/oferta-moderninha-profit-do-pagbank-melhores-taxas-squeeze": [
      a,
      n,
      o,
      f,
      "static/css/2862c9fb77d6c653.css",
      "static/chunks/pages/oferta-moderninha-profit-do-pagbank-melhores-taxas-squeeze-517dab479b929a18.js",
    ],
    "/oferta-moderninha-profit-do-pagbank-squeeze": [
      a,
      n,
      o,
      "static/css/603d06445f6bfc6d.css",
      "static/chunks/pages/oferta-moderninha-profit-do-pagbank-squeeze-27a1a6a23cd12ae5.js",
    ],
    "/oferta-moderninha-smart2-do-pagbank": [
      "static/chunks/pages/oferta-moderninha-smart2-do-pagbank-c8521e31d32a4916.js",
    ],
    "/oferta-moderninha-smart2-do-pagbank-melhores-taxas-squeeze": [
      a,
      n,
      o,
      f,
      "static/css/8e1f2e511fe5c8d8.css",
      "static/chunks/pages/oferta-moderninha-smart2-do-pagbank-melhores-taxas-squeeze-88cec158efe73cd5.js",
    ],
    "/oferta-moderninha-smart2-do-pagbank-squeeze": [
      a,
      n,
      o,
      "static/css/c46889ec2eb68b1c.css",
      "static/chunks/pages/oferta-moderninha-smart2-do-pagbank-squeeze-361922c61cb911fe.js",
    ],
    "/oferta-moderninha-smart2-do-pagseguro": [
      "static/chunks/pages/oferta-moderninha-smart2-do-pagseguro-945dd72df77300cc.js",
    ],
    "/pagcontrole-assinatura-maquininha": [
      x,
      "static/css/b25e0abf36c1c22f.css",
      "static/chunks/pages/pagcontrole-assinatura-maquininha-0d07cc3b487d0db1.js",
    ],
    "/pagvendas-loja-online-cupons": [
      "static/css/d9968fc7ce789aa4.css",
      "static/chunks/pages/pagvendas-loja-online-cupons-a326b6ce22e6fa62.js",
    ],
    "/pre-black-friday": [
      s,
      e,
      u,
      j,
      "static/css/c5cd4a4ce5924055.css",
      "static/chunks/pages/pre-black-friday-98fa0e9949228c1d.js",
    ],
    "/quiz-maquininha-ideal-para-seu-negocio": [
      v,
      "static/css/6151f9747f3d6f32.css",
      "static/chunks/pages/quiz-maquininha-ideal-para-seu-negocio-a08afe9014e1d134.js",
    ],
    "/quiz-maquininha-ideal-para-seu-negocio/resultado/[sku]": [
      v,
      "static/css/8fa8e36951234dc3.css",
      "static/chunks/pages/quiz-maquininha-ideal-para-seu-negocio/resultado/[sku]-e77a7db3dc755d28.js",
    ],
    "/rendaextra": [
      "static/css/57e23399ce59a151.css",
      "static/chunks/pages/rendaextra-189103571bff20a2.js",
    ],
    "/sorteiomensal": [
      x,
      "static/css/a1cd8a35a2942b9c.css",
      "static/chunks/pages/sorteiomensal-f3ff7d9c0165210d.js",
    ],
    "/tap-on": ["static/chunks/pages/tap-on-8e3d5188e2b389e9.js"],
    "/tap-on-no-pagbank": [
      h,
      _,
      y,
      "static/css/a24a2b0f21821c49.css",
      "static/chunks/pages/tap-on-no-pagbank-99f988b454af08c7.js",
    ],
    "/tap-on-pagbank": [
      h,
      _,
      y,
      "static/css/8923498fc2778945.css",
      "static/chunks/pages/tap-on-pagbank-6b5f97aaa0324772.js",
    ],
    "/tap-on-pagvendas": [
      "static/chunks/pages/tap-on-pagvendas-f41e8f4e65dda8e0.js",
    ],
    "/tap-to-pay-iphone-pagbank": [
      "static/css/68a3d0dcb9e75622.css",
      "static/chunks/pages/tap-to-pay-iphone-pagbank-b5e4a512617fc36f.js",
    ],
    "/taponpagvendas": [
      "static/chunks/pages/taponpagvendas-118849e3d567b5d2.js",
    ],
    "/venda": [
      s,
      e,
      c,
      t,
      r,
      a,
      i,
      d,
      I,
      B,
      "static/chunks/pages/venda-312b9464c483a477.js",
    ],
    "/vender": [
      s,
      e,
      c,
      t,
      r,
      a,
      i,
      d,
      I,
      B,
      "static/chunks/pages/vender-28c81cd02da9a028.js",
    ],
    sortedPages: [
      "/50vezeseducacaofinanceira",
      "/_app",
      "/_error",
      "/antecipacao-saque-fgts",
      "/autonomos",
      "/baixe-pagbank-fgts",
      "/beleza-e-estetica",
      "/calculadora-de-desconto",
      "/campanha-pix-vtex",
      "/cashback-pagbank-na-maquina",
      "/cashback-turbinado",
      "/clientes-reais",
      "/combo-maquininhas-e-cartao",
      "/consignado-inss",
      "/contato",
      "/diversificacao-com-fundos",
      "/emprestimo-consignado-siape",
      "/evento",
      "/folha-de-pagamento",
      "/gerador-url-eventos",
      "/maquinas-cartao-taxas-faturamento",
      "/maquinas-de-cartao",
      "/maquinas-de-cartao/condicoes-especiais",
      "/maquinas-de-cartao/moderninhas",
      "/maquinas-de-cartao/promo-especial",
      "/maquinas-de-cartao/sazonal",
      "/maquinas-de-cartao/tap-on",
      "/maquinas-de-cartao/v2",
      "/maquinas-de-cartao-promo-elo",
      "/maquininha-de-cartao-menores-taxas",
      "/maquininha-pagbank-oferta-exclusiva",
      "/maquininhas-de-cartao-melhores-taxas",
      "/maquininhas-taxas-planos",
      "/motoristas-e-taxistas",
      "/oferta-minizinha-chip3-do-pagbank-melhores-taxas-squeeze",
      "/oferta-minizinha-chip3-do-pagbank-squeeze",
      "/oferta-minizinha-chip3-do-pagseguro-squeeze",
      "/oferta-minizinha-nfc2-do-pagbank",
      "/oferta-minizinha-nfc2-do-pagbank-melhores-taxas-squeeze",
      "/oferta-minizinha-nfc2-do-pagbank-squeeze",
      "/oferta-minizinha-nfc2-do-pagseguro",
      "/oferta-minizinha-nfc2-do-pagseguro-squeeze",
      "/oferta-moderninha-plus2-do-pagbank-melhores-taxas-squeeze",
      "/oferta-moderninha-plus2-do-pagbank-squeeze",
      "/oferta-moderninha-plus2-do-pagseguro-squeeze",
      "/oferta-moderninha-pro-do-pagbank-squeeze",
      "/oferta-moderninha-pro-do-pagseguro-squeeze",
      "/oferta-moderninha-pro2-do-pagbank-melhores-taxas-squeeze",
      "/oferta-moderninha-pro2-do-pagbank-squeeze",
      "/oferta-moderninha-pro2-do-pagseguro-squeeze",
      "/oferta-moderninha-profit-do-pagbank-melhores-taxas-squeeze",
      "/oferta-moderninha-profit-do-pagbank-squeeze",
      "/oferta-moderninha-smart2-do-pagbank",
      "/oferta-moderninha-smart2-do-pagbank-melhores-taxas-squeeze",
      "/oferta-moderninha-smart2-do-pagbank-squeeze",
      "/oferta-moderninha-smart2-do-pagseguro",
      "/pagcontrole-assinatura-maquininha",
      "/pagvendas-loja-online-cupons",
      "/pre-black-friday",
      "/quiz-maquininha-ideal-para-seu-negocio",
      "/quiz-maquininha-ideal-para-seu-negocio/resultado/[sku]",
      "/rendaextra",
      "/sorteiomensal",
      "/tap-on",
      "/tap-on-no-pagbank",
      "/tap-on-pagbank",
      "/tap-on-pagvendas",
      "/tap-to-pay-iphone-pagbank",
      "/taponpagvendas",
      "/venda",
      "/vender",
    ],
  };
})(
  "static/chunks/4877-7fd834cc1e5de04e.js",
  "static/css/886449c591c6b4d5.css",
  "static/chunks/1292-769b101c89cb5ab3.js",
  "static/css/026cc4db2cb1c4aa.css",
  "static/chunks/8893-7899a54d1ab542e4.js",
  "static/css/84bf6d6831e4f108.css",
  "static/chunks/3752-c12183daf8fc6290.js",
  "static/css/35ccd2dd9f21f16b.css",
  "static/chunks/569-fcc342a6180188ff.js",
  "static/css/08ecabc282337036.css",
  "static/chunks/9491-246ae875acb5f99c.js",
  "static/chunks/6712-9edbe3b9ab04f4ff.js",
  "static/chunks/5264-5bf688b13f6b4e0c.js",
  "static/chunks/9198-19830d82b7ca2231.js",
  "static/css/8b790a5669b428aa.css",
  "static/chunks/675-8984cdee299b9fa5.js",
  "static/css/f89f4e1d4061469c.css",
  "static/chunks/6438-ba90b4748f0c1665.js",
  "static/chunks/3092-4d8acb10287e9741.js",
  "static/chunks/8760-424f219d995d8820.js",
  "static/chunks/2733-4089c8da085cd714.js",
  "static/chunks/2011-4d177718aee3c95c.js",
  "static/chunks/6573-41970d582908b03a.js",
  "static/chunks/3492-98e05532716ae98a.js",
  "static/css/3a9d6f8f493b99d3.css",
  "static/chunks/7972-752b55aa5e765dc8.js",
  "static/chunks/3085-2a3ed0d79f853e7e.js",
  "static/css/26c389d39f15c925.css"
)),
  self.__BUILD_MANIFEST_CB && self.__BUILD_MANIFEST_CB();
